insert into public.features (id, name) values
  (uuid_generate_v4(), 'Restaurant'),
  (uuid_generate_v4(), 'Bar'),
  (uuid_generate_v4(), 'Beachbar'),
  (uuid_generate_v4(), 'Cafe'),
  (uuid_generate_v4(), 'Bakery'),
  (uuid_generate_v4(), 'Supermarket'),
  (uuid_generate_v4(), 'Pool'),
  (uuid_generate_v4(), 'Indoor Pool'),
  (uuid_generate_v4(), 'Sauna'),
  (uuid_generate_v4(), 'Wellness'),
  (uuid_generate_v4(), 'Fitness'),
  (uuid_generate_v4(), 'Lake'),
  (uuid_generate_v4(), 'Sea'),
  (uuid_generate_v4(), 'River'),
  (uuid_generate_v4(), 'Beach'),
  (uuid_generate_v4(), 'Dog Beach'),
  (uuid_generate_v4(), 'SUP'),
  (uuid_generate_v4(), 'Kayak'),
  (uuid_generate_v4(), 'Boat Rental'),
  (uuid_generate_v4(), 'Bike Rental'),
  (uuid_generate_v4(), 'E-Bike Rental'),
  (uuid_generate_v4(), 'Playground'),
  (uuid_generate_v4(), 'Animation'),
  (uuid_generate_v4(), 'Live Music'),
  (uuid_generate_v4(), 'Events'),
  (uuid_generate_v4(), 'WiFi'),
  (uuid_generate_v4(), 'Washing Machine'),
  (uuid_generate_v4(), 'Dryer'),
  (uuid_generate_v4(), 'Electricity'),
  (uuid_generate_v4(), 'Fresh Water'),
  (uuid_generate_v4(), 'Waste Water'),
  (uuid_generate_v4(), 'Chemical Toilet Disposal'),
  (uuid_generate_v4(), 'Motorhome Service');
